// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJCyrHr06LnUxH985WdNgDK7HldQmhc70',
    appId: '1:32601902910:web:6d73fbcea7f127bc6ee66f',
    messagingSenderId: '32601902910',
    projectId: 'fir-demo-46a76',
    authDomain: 'fir-demo-46a76.firebaseapp.com',
    storageBucket: 'fir-demo-46a76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuVdTfjDxk95dDokdfqEyBGC_fOZ8rCRY',
    appId: '1:32601902910:android:5dacd2b03ac5d7fa6ee66f',
    messagingSenderId: '32601902910',
    projectId: 'fir-demo-46a76',
    storageBucket: 'fir-demo-46a76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBZEw1eSSn4cX_F7Ps5SLFiDtq1D0780E',
    appId: '1:32601902910:ios:5709c17faf35b4b16ee66f',
    messagingSenderId: '32601902910',
    projectId: 'fir-demo-46a76',
    storageBucket: 'fir-demo-46a76.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
